web:
  build: ./lights-web
  ports:
   - "3000:3000"
  volumes:
   - ./lights-web/src:/usr/src/app/src
  environment:
   - NODE_ENV=development
lightsgetcolour-nodejs:
  build: ./lightsGetColour-nodejs
  ports:
    - "3010:3010"
  volumes:
   - ./:/home/pi/kidsLights
   - ./lightsGetColour-nodejs:/usr/src/app
  environment:
   - NODE_ENV=development
